### PR TITLE
It should be converted to number first before sort

### PR DESCRIPTION
**Pull request by donghopark**

### CODE REVIEW

**Comment by donghopark** [comment]
Hi. Ashish. Your plugin is really nice. Thanks a lot. I'm using this plugin and found one bug. When I set thresholds with various values, it just didn't recognize well. Please see my pull request.

**Comment by ashish-chopra** [comment]
Thanks @donghopark for using it. I am glad that you found it useful. 
I saw your modifications in the pull request. But can you please explain and write some cases which you tried so that i can reproduce the issue at my side?

Thanks
Ashish

**Comment by donghopark** [comment]
You may try with below configuration

$scope.gaugeThreshold = {      
      '0': {color: '#228B22'},
      '8': {color: "#AABC22"},
      '21': {color: '#FFF54C'},      
      '31': {color: '#DF9111'},
      '41': {color: '#FF0000'},
    }

$scope.value = 22;

It should be third option to be selected, but once it go over 8, it always select the second option.

**Comment by ashish-chopra** [comment]
#46

**Comment by ashish-chopra** [comment]
Hi @donghopark 

I tested your code, its working fine, with one simple change that you need to push in your pull request, so that build will pass.

change
```
.sort((a,b) => {Number(a) > Number(b)})
```
to
```
.sort(function(a,b) {return Number(a) > Number(b);}
```

**Comment by donghopark** [comment]
Re-commited as you recommend

**Pull request merged**
